version: 2.1
orbs:
  cypress: cypress-io/cypress@2.2.0
workflows:
  build:
    jobs:
        - cypress/install
        - cypress/run:
             name: "TS1"
             install-command: npm i
             spec: cypress/e2e/TS1.cy.js

           
           
  
            

        
    